name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Fastlane test lane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'build'

  test:
    name: Debug unit tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Fastlane test lane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'test'
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: |
            **/build/reports/tests/testDebugUnitTest/index.html
  lint:
    name: Lint debug
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint
        run: ./gradlew lint
      - name: Upload linting report
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: |
            **/build/reports/lint-results-debug.html